//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AolussClientLib.Client;
using AolussClientLib.Api;
using AolussClientLib.Model;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing OperationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OperationsApiTests
    {
        private OperationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OperationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OperationsApi
            //Assert.IsInstanceOfType(typeof(OperationsApi), instance, "instance is a OperationsApi");
        }

        /// <summary>
        /// Test DeleteOperatorOperation
        /// </summary>
        [Test]
        public void DeleteOperatorOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? gufi = null;
            //var response = instance.DeleteOperatorOperation(gufi);
            //Assert.IsInstanceOf<ResponseOk> (response, "response is ResponseOk");
        }
        /// <summary>
        /// Test GetOperatorOperation
        /// </summary>
        [Test]
        public void GetOperatorOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? gufi = null;
            //instance.GetOperatorOperation(gufi);
            
        }
        /// <summary>
        /// Test PostOperatorMessage
        /// </summary>
        [Test]
        public void PostOperatorMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ModelOperatorMessage body = null;
            //instance.PostOperatorMessage(body);
            
        }
        /// <summary>
        /// Test PostOperatorPosition
        /// </summary>
        [Test]
        public void PostOperatorPositionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ModelOperatorPosition body = null;
            //instance.PostOperatorPosition(body);
            
        }
        /// <summary>
        /// Test PutOperatorOperation
        /// </summary>
        [Test]
        public void PutOperatorOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ModelOperatorOperation body = null;
            //instance.PutOperatorOperation(body);
            
        }
    }

}
