FROM adamrehn/ue4-engine:4.19.2-cudagl10.0

USER root
RUN apt-get update
RUN apt-get install \
	rsync \
    sudo \
    wget \
    x11-xserver-utils \
    -y --no-install-recommends

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \ 
    adduser ue4 sudo 

USER ue4
RUN cd /home/ue4 && \
	git clone --progress https://github.com/Microsoft/AirSim.git && \
	cd AirSim && \
	./setup.sh && \
	./build.sh
	
WORKDIR /home/ue4
