ARG BASE_IMAGE=adamrehn/ue4-engine:4.19.2-cudagl10.0
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	rsync \
    sudo \
    wget \
    x11-xserver-utils

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    adduser ue4 sudo 

USER ue4
RUN cd /home/ue4 && \
	git clone --progress https://github.com/Microsoft/AirSim.git && \
	cd AirSim && \
	./setup.sh && \
	./build.sh

WORKDIR /home/ue4
