//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AolussClientLib.Api;
using AolussClientLib.Model;
using AolussClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing ModelOperatorOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelOperatorOperationTests
    {
        // TODO uncomment below to declare an instance variable for ModelOperatorOperation
        //private ModelOperatorOperation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelOperatorOperation
            //instance = new ModelOperatorOperation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelOperatorOperation
        /// </summary>
        [Test]
        public void ModelOperatorOperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelOperatorOperation
            //Assert.IsInstanceOfType<ModelOperatorOperation> (instance, "variable 'instance' is a ModelOperatorOperation");
        }


        /// <summary>
        /// Test the property 'Gufi'
        /// </summary>
        [Test]
        public void GufiTest()
        {
            // TODO unit test for the property 'Gufi'
        }
        /// <summary>
        /// Test the property 'UasRegistrations'
        /// </summary>
        [Test]
        public void UasRegistrationsTest()
        {
            // TODO unit test for the property 'UasRegistrations'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'ControllerLocation'
        /// </summary>
        [Test]
        public void ControllerLocationTest()
        {
            // TODO unit test for the property 'ControllerLocation'
        }
        /// <summary>
        /// Test the property 'GcsLocation'
        /// </summary>
        [Test]
        public void GcsLocationTest()
        {
            // TODO unit test for the property 'GcsLocation'
        }
        /// <summary>
        /// Test the property 'FaaRule'
        /// </summary>
        [Test]
        public void FaaRuleTest()
        {
            // TODO unit test for the property 'FaaRule'
        }
        /// <summary>
        /// Test the property 'OperationVolumes'
        /// </summary>
        [Test]
        public void OperationVolumesTest()
        {
            // TODO unit test for the property 'OperationVolumes'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'AircraftComments'
        /// </summary>
        [Test]
        public void AircraftCommentsTest()
        {
            // TODO unit test for the property 'AircraftComments'
        }
        /// <summary>
        /// Test the property 'FlightComments'
        /// </summary>
        [Test]
        public void FlightCommentsTest()
        {
            // TODO unit test for the property 'FlightComments'
        }
        /// <summary>
        /// Test the property 'VolumesDescription'
        /// </summary>
        [Test]
        public void VolumesDescriptionTest()
        {
            // TODO unit test for the property 'VolumesDescription'
        }
        /// <summary>
        /// Test the property 'AirspaceAuthorization'
        /// </summary>
        [Test]
        public void AirspaceAuthorizationTest()
        {
            // TODO unit test for the property 'AirspaceAuthorization'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Test]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }
        /// <summary>
        /// Test the property 'ContingencyPlans'
        /// </summary>
        [Test]
        public void ContingencyPlansTest()
        {
            // TODO unit test for the property 'ContingencyPlans'
        }
        /// <summary>
        /// Test the property 'PriorityElements'
        /// </summary>
        [Test]
        public void PriorityElementsTest()
        {
            // TODO unit test for the property 'PriorityElements'
        }

    }

}
