//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AolussClientLib.Api;
using AolussClientLib.Model;
using AolussClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing ModelOperatorMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelOperatorMessageTests
    {
        // TODO uncomment below to declare an instance variable for ModelOperatorMessage
        //private ModelOperatorMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelOperatorMessage
            //instance = new ModelOperatorMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelOperatorMessage
        /// </summary>
        [Test]
        public void ModelOperatorMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelOperatorMessage
            //Assert.IsInstanceOfType<ModelOperatorMessage> (instance, "variable 'instance' is a ModelOperatorMessage");
        }


        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Test]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
        /// <summary>
        /// Test the property 'Gufi'
        /// </summary>
        [Test]
        public void GufiTest()
        {
            // TODO unit test for the property 'Gufi'
        }
        /// <summary>
        /// Test the property 'TimeSent'
        /// </summary>
        [Test]
        public void TimeSentTest()
        {
            // TODO unit test for the property 'TimeSent'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Test]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Test]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }
        /// <summary>
        /// Test the property 'PrevMessageId'
        /// </summary>
        [Test]
        public void PrevMessageIdTest()
        {
            // TODO unit test for the property 'PrevMessageId'
        }
        /// <summary>
        /// Test the property 'FreeText'
        /// </summary>
        [Test]
        public void FreeTextTest()
        {
            // TODO unit test for the property 'FreeText'
        }

    }

}
