//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AolussClientLib.Api;
using AolussClientLib.Model;
using AolussClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing ModelOperatorPosition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelOperatorPositionTests
    {
        // TODO uncomment below to declare an instance variable for ModelOperatorPosition
        //private ModelOperatorPosition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelOperatorPosition
            //instance = new ModelOperatorPosition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelOperatorPosition
        /// </summary>
        [Test]
        public void ModelOperatorPositionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelOperatorPosition
            //Assert.IsInstanceOfType<ModelOperatorPosition> (instance, "variable 'instance' is a ModelOperatorPosition");
        }


        /// <summary>
        /// Test the property 'AltitudeGps'
        /// </summary>
        [Test]
        public void AltitudeGpsTest()
        {
            // TODO unit test for the property 'AltitudeGps'
        }
        /// <summary>
        /// Test the property 'EnroutePositionsId'
        /// </summary>
        [Test]
        public void EnroutePositionsIdTest()
        {
            // TODO unit test for the property 'EnroutePositionsId'
        }
        /// <summary>
        /// Test the property 'Gufi'
        /// </summary>
        [Test]
        public void GufiTest()
        {
            // TODO unit test for the property 'Gufi'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'TimeMeasured'
        /// </summary>
        [Test]
        public void TimeMeasuredTest()
        {
            // TODO unit test for the property 'TimeMeasured'
        }
        /// <summary>
        /// Test the property 'VdopGps'
        /// </summary>
        [Test]
        public void VdopGpsTest()
        {
            // TODO unit test for the property 'VdopGps'
        }
        /// <summary>
        /// Test the property 'HdopGps'
        /// </summary>
        [Test]
        public void HdopGpsTest()
        {
            // TODO unit test for the property 'HdopGps'
        }
        /// <summary>
        /// Test the property 'AltitudeNumGpsSatellites'
        /// </summary>
        [Test]
        public void AltitudeNumGpsSatellitesTest()
        {
            // TODO unit test for the property 'AltitudeNumGpsSatellites'
        }
        /// <summary>
        /// Test the property 'TrackBearingReference'
        /// </summary>
        [Test]
        public void TrackBearingReferenceTest()
        {
            // TODO unit test for the property 'TrackBearingReference'
        }
        /// <summary>
        /// Test the property 'TrackBearing'
        /// </summary>
        [Test]
        public void TrackBearingTest()
        {
            // TODO unit test for the property 'TrackBearing'
        }
        /// <summary>
        /// Test the property 'TrackBearingUom'
        /// </summary>
        [Test]
        public void TrackBearingUomTest()
        {
            // TODO unit test for the property 'TrackBearingUom'
        }
        /// <summary>
        /// Test the property 'TrackGroundSpeed'
        /// </summary>
        [Test]
        public void TrackGroundSpeedTest()
        {
            // TODO unit test for the property 'TrackGroundSpeed'
        }
        /// <summary>
        /// Test the property 'TrackGroundSpeedUnits'
        /// </summary>
        [Test]
        public void TrackGroundSpeedUnitsTest()
        {
            // TODO unit test for the property 'TrackGroundSpeedUnits'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }

    }

}
