//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AolussClientLib.Api;
using AolussClientLib.Model;
using AolussClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing ModelAltitudeFixm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelAltitudeFixmTests
    {
        // TODO uncomment below to declare an instance variable for ModelAltitudeFixm
        //private ModelAltitudeFixm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelAltitudeFixm
            //instance = new ModelAltitudeFixm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelAltitudeFixm
        /// </summary>
        [Test]
        public void ModelAltitudeFixmInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelAltitudeFixm
            //Assert.IsInstanceOfType<ModelAltitudeFixm> (instance, "variable 'instance' is a ModelAltitudeFixm");
        }


        /// <summary>
        /// Test the property 'AltitudeValue'
        /// </summary>
        [Test]
        public void AltitudeValueTest()
        {
            // TODO unit test for the property 'AltitudeValue'
        }
        /// <summary>
        /// Test the property 'VerticalReference'
        /// </summary>
        [Test]
        public void VerticalReferenceTest()
        {
            // TODO unit test for the property 'VerticalReference'
        }
        /// <summary>
        /// Test the property 'UnitsOfMeasure'
        /// </summary>
        [Test]
        public void UnitsOfMeasureTest()
        {
            // TODO unit test for the property 'UnitsOfMeasure'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
