//*****************************************************************************
//* Project: Firefly (Microsoft Hackaton 2020)
//* Description: AOLUSS REST Client
//* Author: Mark West (mark.west@microsoft.com)
//*****************************************************************************

/* 
 * NASA AOLUSS Operator interface
 *
 * this OAS document describes the operator interface for the AOLUSS.
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AolussClientLib.Api;
using AolussClientLib.Model;
using AolussClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AolussClientLib.Test
{
    /// <summary>
    ///  Class for testing ModelMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelMetadataTests
    {
        // TODO uncomment below to declare an instance variable for ModelMetadata
        //private ModelMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelMetadata
            //instance = new ModelMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelMetadata
        /// </summary>
        [Test]
        public void ModelMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelMetadata
            //Assert.IsInstanceOfType<ModelMetadata> (instance, "variable 'instance' is a ModelMetadata");
        }


        /// <summary>
        /// Test the property 'DataCollection'
        /// </summary>
        [Test]
        public void DataCollectionTest()
        {
            // TODO unit test for the property 'DataCollection'
        }
        /// <summary>
        /// Test the property 'Scenario'
        /// </summary>
        [Test]
        public void ScenarioTest()
        {
            // TODO unit test for the property 'Scenario'
        }
        /// <summary>
        /// Test the property 'TestCard'
        /// </summary>
        [Test]
        public void TestCardTest()
        {
            // TODO unit test for the property 'TestCard'
        }
        /// <summary>
        /// Test the property 'CallSign'
        /// </summary>
        [Test]
        public void CallSignTest()
        {
            // TODO unit test for the property 'CallSign'
        }
        /// <summary>
        /// Test the property 'TestType'
        /// </summary>
        [Test]
        public void TestTypeTest()
        {
            // TODO unit test for the property 'TestType'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Test]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Setting'
        /// </summary>
        [Test]
        public void SettingTest()
        {
            // TODO unit test for the property 'Setting'
        }
        /// <summary>
        /// Test the property 'FreeText'
        /// </summary>
        [Test]
        public void FreeTextTest()
        {
            // TODO unit test for the property 'FreeText'
        }

    }

}
