name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@aecc1901f080e23c1bab6ccb1b2daa8d50eda274 # v4.4.1
      with:
        clang-format-version: '11'
        check-path: '.'
        exclude-regex: 'AirLib\/include\/common\/common_utils\/json\.hpp'
