name: Windows Build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Build AirLib
        shell: cmd
        run: build.cmd

      - name: Unity build
        shell: cmd
        run: |
          cd Unity
          build.cmd
